     plt.plot(thIK); hold on;
  set(supportLines, 'xdata', xOrdered(1,:), 'ydata',xOrdered(2,:), ...
     'zdata', xOrdered(3,:));
  inSupport = inpolygon(projBodyCoMRot(1),projBodyCoMRot(2),xOrderedRot(1,:),xOrderedRot(2,:));
  set(projectedCOM, 'xdata', projBodyCoM(1), 'ydata',projBodyCoM(2), 'zdata', projBodyCoM(3),...
     'markerFaceColor', [1 0 0]*~inSupport);
%   set(scatterCentroid, 'xdata', xCentroid(1), 'ydata',xCentroid(2), 'zdata',xCentroid(3));
%  set(planeArrow,...
%      'udata', TP_B(1,3)*.1,'vdata', TP_B(2,3)*.1,'wdata', TP_B(3,3)*.1,...
%      'xdata', TP_B(1,4),'ydata', TP_B(2,4),'zdata', TP_B(3,4));
         % scatter3(xyzFK(1,:), xyzFK(2,:), xyzFK(3,:), 'r');
        %                 scatter3(xyzB(1,:), xyzB(2,:), xyzB(3,:), [], swingLegs, 'filled');
        